In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

cc_df=pd.read_csv('Data/creditcard.csv')
cc_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [2]:
cc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [3]:
from sklearn.model_selection import train_test_split
train_split=round(len(cc_df)*0.8)
train_set,val_set=cc_df.iloc[:train_split,:],cc_df.iloc[train_split:,:]  #Temporal Split instead of Random Split
train_set.shape,val_set.shape

((227846, 31), (56961, 31))

In [4]:
val_set

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
227846,145249.0,2.152696,-0.036161,-2.231811,0.091766,0.537612,-1.368103,0.613327,-0.455252,0.291814,...,0.017153,0.063242,-0.034561,-0.626866,0.249213,0.773931,-0.137115,-0.090611,14.95,0
227847,145249.0,-4.034795,2.305079,-1.461693,-0.729887,-1.528750,-1.225679,-0.893354,1.622522,1.291998,...,-0.392557,-0.787599,0.343468,-0.090331,0.248287,-0.238524,0.266484,-0.062236,7.70,0
227848,145249.0,-1.668741,1.168055,0.249642,-1.268497,0.785923,-0.663959,0.859433,0.068111,-0.144183,...,-0.247544,-0.592537,-0.286694,-0.378856,-0.077429,0.067608,-0.278962,-0.064193,6.99,0
227849,145250.0,-0.550678,-0.429004,-1.291893,-0.414409,-0.292229,0.071843,2.426068,-0.212730,0.412374,...,0.003032,-0.645783,0.877016,-1.228529,-0.036281,-0.110610,-0.098380,0.095985,460.71,0
227850,145250.0,1.846910,0.143301,-1.171846,1.570946,0.076854,-0.858130,0.164378,-0.251494,0.442113,...,-0.018428,0.048949,0.105389,-0.119156,-0.014024,-0.705045,0.044595,0.000922,68.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [5]:
input_cols=['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']
target_col='Class'

In [6]:
train_inputs=train_set[input_cols].copy()
val_inputs=val_set[input_cols].copy()
train_target=train_set[target_col].copy()
val_target=val_set[target_col].copy()

In [16]:
numeric_cols=train_inputs.select_dtypes(include=np.number).columns.tolist()
numeric_cols

['Time',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'Amount']

In [8]:
from sklearn.preprocessing import StandardScaler #Normalised features to have a consistency
scaler=StandardScaler()
scaler.fit(train_inputs[numeric_cols])

StandardScaler()

In [9]:
train_inputs[numeric_cols]=scaler.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols]=scaler.transform(val_inputs[numeric_cols])

In [10]:
import mlflow
import mlflow.sklearn

In [11]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_auc_score #precision and recall matters more than accuracy due to severe class imabalance
def model_evaluate(model):
    train_preds=model.predict(train_inputs)
    val_preds=model.predict(val_inputs)
    train_acc=accuracy_score(train_target,train_preds)
    val_acc=accuracy_score(val_target,val_preds)
    train_prec=precision_score(train_target,train_preds)   
    val_prec=precision_score(val_target,val_preds)
    train_rec=recall_score(train_target,train_preds)   
    val_rec=recall_score(val_target,val_preds)   
    train_roc=roc_auc_score(train_target,train_preds)
    val_roc=roc_auc_score(val_target,val_preds)
    print(f'Train Results: Acc ==> {train_acc}, Precision ==>{train_prec},Recall ==> {train_rec},ROC-AUC ==> {train_roc}')
    print(f'Val Results: Acc ==> {val_acc}, Precsion ==>{val_prec}, Recall ==> {val_rec},ROC-AUC ==>{val_roc}')
    mlflow.log_metric('Train_Accuracy',train_acc)
    mlflow.log_metric('Test_Accuracy',val_acc)
    mlflow.log_metric('Train_Precision',train_prec)
    mlflow.log_metric('Test_Precision',val_prec)
    mlflow.log_metric('Train_Recall',train_rec)
    mlflow.log_metric('Test_Recall',val_rec)
    mlflow.log_metric('Train_ROC-AUC',train_roc)
    mlflow.log_metric('Test_ROC-AUC',val_roc)

In [27]:
mlflow.set_experiment('Credit Card Fraud Detection ==> Classification')

<Experiment: artifact_location='file:///c:/KM/Coding%21%21%21/vs%20code/Scikit%20Learn/Credit%20Card%20Fraud%20Detection/mlruns/317037929740553959', creation_time=1761141651740, experiment_id='317037929740553959', last_update_time=1761141651740, lifecycle_stage='active', name='Credit Card Fraud Detection ==> Classification', tags={'mlflow.experimentKind': 'custom_model_development'}>

In [ ]:
from sklearn.linear_model import LogisticRegression # Using this as Baseline Model
with mlflow.start_run(run_name='Logistic_Regression_V2'):
     mlflow.set_tag('description','Earlier Random Splitting was used, now this new run has temporal split (80-20)')
     model_log=LogisticRegression(class_weight='balanced')
     model_log.fit(train_inputs,train_target)
     mlflow.log_params(model_log.get_params())
     model_evaluate(model_log)

Train Results: Acc ==> 0.9795827005960166, Precision ==>0.07709207110045936,Recall ==> 0.9256594724220624,ROC-AUC ==> 0.9526705216869379
Val Results: Acc ==> 0.9844103860536156, Precsion ==>0.07074973600844774, Recall ==> 0.8933333333333333,ROC-AUC ==>0.9389318988854902

In [29]:
from sklearn.tree import DecisionTreeClassifier
with mlflow.start_run(run_name='Descision_Tree v3'):
   mlflow.set_tag('description','Earlier Random Splitting was used, now this new run has temporal split (80-20)')
   model_tree=DecisionTreeClassifier(max_depth=8,random_state=42,class_weight='balanced')
   model_tree.fit(train_inputs,train_target)
   mlflow.log_params(model_tree.get_params())
   model_evaluate(model_tree)

Train Results: Acc ==> 0.9849591390676159, Precision ==>0.10827693909422176,Recall ==> 0.9976019184652278,ROC-AUC ==> 0.9912689382502413
Val Results: Acc ==> 0.987026210916241, Precsion ==>0.07435897435897436, Recall ==> 0.7733333333333333,ROC-AUC ==>0.880320641282565

In [31]:
from sklearn.ensemble import RandomForestClassifier
with mlflow.start_run(run_name='Random_Forest v5'):
   mlflow.set_tag('description','Earlier Random Splitting was used, now this new run has temporal split (80-20)')
   model_forest=RandomForestClassifier(n_jobs=-1,n_estimators=120,max_depth=8,random_state=42,class_weight='balanced')
   model_forest.fit(train_inputs,train_target)
   mlflow.log_params(model_forest.get_params())
   model_evaluate(model_forest)

Train Results: Acc ==> 0.9996225520746469, Precision ==>0.8653421633554084,Recall ==> 0.9400479616306955,ROC-AUC ==> 0.9698898730278623
Val Results: Acc ==> 0.9996137708256526, Precsion ==>0.9206349206349206, Recall ==> 0.7733333333333333,ROC-AUC ==>0.8866227191224555

In [34]:
from xgboost import XGBClassifier
with mlflow.start_run(run_name='XGB v5'):
   from sklearn.utils.class_weight import compute_sample_weight
   sample_weight=compute_sample_weight(class_weight='balanced',y=train_target)
   mlflow.set_tag('description','Earlier Random Splitting was used, now this new run has temporal split (80-20)')
   model_xgb=XGBClassifier(n_jobs=-1,n_estimators=55,max_depth=6,sample_weight=sample_weight,random_state=42)
   model_xgb.fit(train_inputs,train_target)
   mlflow.log_params(model_xgb.get_params())
   model_evaluate(model_xgb)

c:\Users\KARAN MATTOO\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\training.py:183: UserWarning: [03:10:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "sample_weight" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Train Results: Acc ==> 0.999969277494448, Precision ==>1.0,Recall ==> 0.9832134292565947,ROC-AUC ==> 0.9916067146282974
Val Results: Acc ==> 0.999420656238479, Precsion ==>0.8888888888888888, Recall ==> 0.64,ROC-AUC ==>0.8199472629469466

In [ ]:
from joblib import dump
dump(model_forest,'Models/rf.pkl') #saved the best model i.e. Random Forest

['Models/rf.pkl']

In [15]:
import joblib
joblib.dump(scaler,'Models/classification_scaler.pkl')

['Models/classification_scaler.pkl']